from pypdf import PdfReader
import re


def extract_text_from_pdf(uploaded_file):
    reader = PdfReader(uploaded_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text


def generate_short_explanations(detected):
    insights = []

    if detected["third_party"]:
        insights.append(("High", "User data may be shared with third parties."))

    if detected["tracking"]:
        insights.append(("Medium", "Tracking technologies are used to monitor user behavior."))

    if detected["vague_consent"]:
        insights.append(("Medium", "Vague consent language reduces user control over data."))

    if detected["retention"]:
        insights.append(("Medium", "The duration for storing user data is unclear."))

    if detected["data_collection"]:
        insights.append(("Low", "The policy collects personal or device-related information."))

    if not insights:
        insights.append(("Low", "No significant privacy risks were detected."))

    return insights


def generate_report(risk_level, insights):
    report = "PRIVACY POLICY ANALYSIS REPORT\n"
    report += "=" * 40 + "\n\n"
    report += f"Overall Risk Level: {risk_level}\n\n"
    report += "Key Privacy Insights:\n"

    for i, insight in enumerate(insights, 1):
        report += f"{i}. {insight[1]}\n"

    report += "\nGenerated by AI-Based Privacy Policy Analyzer\n"
    return report


def highlight_risky_terms(text, detected):
    highlighted = text

    for group in detected.values():
        for sentence in group:
            escaped = re.escape(sentence)
            highlighted = re.sub(
                escaped,
                f"<mark>{sentence}</mark>",
                highlighted,
                flags=re.IGNORECASE
            )

    return highlighted
